export const statusLists = [
    { text: "Đơn mới", value: "New" },
    { text: "Đang xác nhận", value: "Confirming" },
    { text: "Chờ khách xác nhận", value: "CustomerConfirming" },
    { text: "Đã xác nhận", value: "Confirmed" },
    { text: "Đang đóng gói", value: "Packing" },
    { text: "Đã đóng gói", value: "Packed" },
    { text: "Đổi kho xuất hàng", value: "ChangeDepot" },
    { text: "Chờ thu gom", value: "Pickup" },
    { text: "Đang giao hàng", value: "Shipping" },
    { text: "Thành công", value: "Success" },
    { text: "Thất bại", value: "Failed" },
    { text: "Khách hủy", value: "Canceled" },
    { text: "Hệ thống hủy", value: "Aborted" },
    { text: "Hãng vận chuyển hủy đơn", value: "CarrierCanceled" },
    { text: "Hết hàng", value: "SoldOut" },
    { text: "Đang chuyển hoàn", value: "Returning" },
    { text: "Đã chuyển hoàn", value: "Returned" },
  ];